### ISSUE TITLE
Can't join server

### ISSUE THREAD

**Issue by sternschnaube** [Erb3/Cactusfix#4]
Using the latest mod and Minecraft version.

```
Error sending packet clientbound/minecraft:custom_payload
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (cactusfix:sync_freer_cactus_placing)
        at net.minecraft.class_9136.handler$bio000$fabric-networking-api-v1$encode(class_9136.java:547) ~[server-intermediary.jar:?]
        at net.minecraft.class_9136.method_56426(class_9136.java:55) ~[server-intermediary.jar:?]
        at net.minecraft.class_9136.encode(class_9136.java:14) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.encode(class_2545.java:12) ~[server-intermediary.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
        at net.minecraft.class_2535$2.write(class_2535.java:518) ~[server-intermediary.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:?]
        at net.minecraft.class_2535.method_36942(class_2535.java:342) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_52917(class_2535.java:337) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassCastException: class github.erb3.fabric.cactusfix.SyncPacket cannot be cast to class net.minecraft.class_8711 (github.erb3.fabric.cactusfix.SyncPacket and net.minecraft.class_8711 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @5700d6b1)
        at net.minecraft.class_9139$6.encode(class_9139.java:42) ~[server-intermediary.jar:?]
        at net.minecraft.class_8710$1.method_56489(class_8710.java:52) ~[server-intermediary.jar:?]
        at net.minecraft.class_8710$1.method_56490(class_8710.java:57) ~[server-intermediary.jar:?]
        at net.minecraft.class_8710$1.encode(class_8710.java:39) ~[server-intermediary.jar:?]
        at net.minecraft.class_9139$8.encode(class_9139.java:81) ~[server-intermediary.jar:?]
        at net.minecraft.class_9139$9.method_56442(class_9139.java:97) ~[server-intermediary.jar:?]
        at net.minecraft.class_9139$9.encode(class_9139.java:87) ~[server-intermediary.jar:?]
        at net.minecraft.class_9136.method_56426(class_9136.java:53) ~[server-intermediary.jar:?]
        ... 32 more
```

**To reproduce**:
1. Start a fabricmc server with Cactusfix
2. Attempt to join the server, also with Cactusfix
3. See error

**Comment by venaminecraft** [comment]
Thanks 😊

**Comment by piprett** [comment]
Thank you for reporting the issue! It should be fixed in the [latest release](https://modrinth.com/mod/cactusfix/version/1.3.2). I also want to thank you for giving a heart on all the releases, I do notice it! 😊
